import mongoose from 'mongoose';

const entrySchema = new mongoose.Schema({
    fileKey: String,
    fileName: String,
    reel: String,
    folioPage: String,
    folioReference: String,
    ledger: String,
    arcMat: String,
    genMat: String,
    entryType: String,
    entryId: String,
    owner: String,
    store: String,
    storeYear: String,
    accountName: String,
    linkedAccOrPerson: [{type : mongoose.Schema.Types.ObjectId, ref:"peopleObject"}],
    prefix: String,
    firstName: String,
    lastName: String,
    suffix: String,
    profession: String,
    location: String,
    year: String,
    month: String,
    day: String,
    entryText: String,
    transactions: [{type : mongoose.Schema.Types.ObjectId, ref:"transactionObject"}],
    people: [String ],
    places: [String ],
    linkedPeople: [{type : mongoose.Schema.Types.ObjectId, ref:"peopleObject"}],
    linkedPlaces: [{type : mongoose.Schema.Types.ObjectId, ref:"placeObject"}],
    quantity: String,
    commodity: String,
    debitCredit: String,
    colony: String,
    moneyType: String,
    cost: {type : mongoose.Schema.Types.ObjectId, ref:"moneyObject"},
    comments: String,
});

const EntryObject = mongoose.model("EntryObject", entrySchema);
export default EntryObject